save_directory: tmp/data/training/TEST
data_name: Brains_testing
processor:
  platform: hardware
  processor_type: cdaq_to_cdaq
  electrode_setup: [["ao8","ao10","ao13","ao11","ao7","ao12","ao14","out"],
                    [8, 10, 13, 11, 7, 12, 14],
                    [0,1,2,3,4,5,6]]
  driver:
    driver_type: local
    activation_channels: [8, 10, 13, 11, 7, 12, 14]
    readout_channels:
    - 2
    input_instrument: cDAQ1Mod4
    output_instrument: cDAQ1Mod3
    trigger_source: cDAQ1/segment1
    amplification: 28.5
    sampling_frequency: 50
    gain_info: 28.5MV/Afor1
    post_gain: 1
  data:
    input_indices: [0,1,2,3,4,5,6]
    input_electrode_no: 7
    shape: 2550
input_data:
  input_distribution: sawtooth
  input_electrodes: 7
  output_electrodes: 1
  input_frequency: [2, 3, 5, 7, 13, 17, 19]
  phase: [-0.57, 0.25, -1.54, 2.17, 0.08, 0.15, -0.65]
  factor: 0.05
  amplitude: [0.9, 0.9, 0.9, 0.9, 0.9, 0.5, 0.5]
  offset: [-0.3,-0.3,-0.3,-0.3,-0.3,-0.2,-0.2]
  ramp_time: 0.5
  batch_time: 50
  number_batches: 3500